### ISSUE TITLE
Question about network weights update in Algorithm 1

### ISSUE THREAD

**Issue by minhquoc0712** [VICO-UoE/DatasetCondensation#19]
Thank you for your amazing work.

Can I ask about line 9 on your Algorithm 1 in your paper? Why do you choose to update network weights based on loss on synthetic data instead of real data?

**Comment by PatrickZH** [comment]
Hi, thanks. Please refer to the Line 7 in the first paragraph of Page 5 in our paper https://openreview.net/pdf?id=94YYh974g3T
Why? Because: 
1. empirically, it works better.
2. the objective of dataset condensation is training models on synthetic data, thus updating models on synthetic data is reasonable and in line with the objective. 
3. recently some works such as IDC modify it by updating models on real data and achieve good results.

**Comment by minhquoc0712** [comment]
I think I have gained more understanding now. Thank you for your respond.
